---
title: "Tablas"
format: pdf
---

```{r}
#| echo: false
#| include: false
#| warning: false
#| message: false

library(tidyverse)
library(haven)
library(ggridges)
library(viridis)
library(scales)
library(labelled)
library(here)
library(knitr)
```


```{r}
#| echo: false
#| include: false
#| warning: false
#| message: false

enadis <- readRDS(here("data", "enadisJOSE.rds")) # Listo
enadis_completa <- readRDS(here("data/enadis_completa.rds")) # Listo
enadis_oc <- readRDS(here("data/enadis_oc.rds")) # Listo

# Tabla de distribución porcentual de la posición en el trabajo según el grado de dificultad en la capacidad. (JOSE)
cuadro_pos_trab_vs_grad_disc <- enadis %>%
  drop_na(Cap_grado, B8a) %>%
  count(Cap_grado, B8a, name = "Cantidad") %>%
  group_by(Cap_grado) %>%
  mutate(Proporcion = Cantidad / sum(Cantidad)) %>%
  ungroup() %>%
  mutate(Proporcion = percent(Proporcion, accuracy = 0.01, decimal.mark = ",")) %>%
  select(-Cantidad) %>%
  pivot_wider(names_from = B8a, values_from = Proporcion, values_fill = "0,00%")

# Tabla de distribución porcentual que muestra la posición en el trabajo según el grado de dificultad en la capacidad (JOSE)
cuadro_condic_actividad_vs_grad_disc <- enadis %>%
  drop_na(Cap_grado, condic_activi) %>%
  count(Cap_grado, condic_activi, name = "Cantidad") %>%
  group_by(Cap_grado) %>%
  mutate(Proporcion = Cantidad / sum(Cantidad)) %>%
  ungroup() %>%
  mutate(Proporcion = percent(Proporcion, accuracy = 0.01, decimal.mark = ",")) %>%
  select(-Cantidad) %>%
  pivot_wider(names_from = condic_activi, values_from = Proporcion, values_fill = "0,00%")

# Tabla de distribución de personas según zona (urbana o rural) y región de planificación, con sus respectivas cantidades y proporciones. (JOSE)
cuadro_discapacidad_region_zona <- enadis %>%
  filter(!is.na(Cap_grado)) %>%  
  count(region, zona, name = "Cantidad") %>%
  group_by(region) %>%
  mutate(Proporcion = Cantidad / sum(Cantidad),
         Proporcion = percent(Proporcion, accuracy = 0.01, decimal.mark = ",")) %>%
  ungroup()

label_col <- var_label(enadis_completa$Grado_discap)

# Tabla de distribución porcentual del ingreso per cápita por grado de discapacidad (DIEGO)
cuadro_ingreso_vs_grado_discap <- enadis_completa %>%
  drop_na(Grado_discap, QUINTIL_INGRESO) %>%
  count(Grado_discap, QUINTIL_INGRESO, name = "Cantidad") %>%
  group_by(Grado_discap) %>%
  mutate(Proporcion = Cantidad / sum(Cantidad)) %>%
  ungroup() %>%
  mutate(Proporcion = percent(Proporcion, accuracy = 0.01, decimal.mark = ",")) %>%
  select(-Cantidad) %>%
  pivot_wider(names_from = QUINTIL_INGRESO, values_from = Proporcion, values_fill = "0,00%") %>%
  rename(!!label_col  := Grado_discap)

# Tabla de distribución de enfermedades crónicas por grado de discapacidad (DIEGO)
cuadro_enfermedades_vs_grado_discap <- enadis_completa %>%
  drop_na(Grado_discap, Tiene_enfer) %>%
  count(Grado_discap, Tiene_enfer, name = "Cantidad") %>%
  group_by(Grado_discap) %>%
  mutate(Proporcion = Cantidad / sum(Cantidad)) %>%
  ungroup() %>%
  mutate(Proporcion = percent(Proporcion, accuracy = 0.01, decimal.mark = ",")) %>%
  select(-Cantidad) %>%
  pivot_wider(names_from = Tiene_enfer, values_from = Proporcion, values_fill = "0,00%") %>%
  rename(!!label_col  := Grado_discap)

# Tabla de necesidad de productos de apoyo según grado de discapacidad (DIEGO)
cuadro_productos_vs_grado_discap <- enadis_completa %>%
  drop_na(Grado_discap, PROD_ASIS) %>%
  count(Grado_discap, PROD_ASIS, name = "Cantidad") %>%
  group_by(Grado_discap) %>%
  mutate(Proporcion = Cantidad / sum(Cantidad)) %>%
  ungroup() %>%
  mutate(Proporcion = percent(Proporcion, accuracy = 0.01, decimal.mark = ",")) %>%
  select(-Cantidad) %>%
  pivot_wider(names_from = PROD_ASIS, values_from = Proporcion, values_fill = "0,00%") %>%
  rename(!!label_col  := Grado_discap)

cuadro_frec_relativa_pos_grado <- enadis_oc %>% 
  count(Cap_grado, B8a) %>% group_by(Cap_grado) %>% 
  mutate(
    Total = sum(n),
    Frecuencia_Relativa = n/Total
  ) %>% ungroup() %>% select(-Total) %>% 
  pivot_wider(
    names_from = B8a,
    values_from = Frecuencia_Relativa,
    values_fill = 0
  ) %>% 
  mutate_if(is.numeric, ~ percent(.x, acurracy = 0.1))

cuadro_promedio_ingreso_vs_pos_y_grado <- enadis_completa %>% 
  filter(!is.na(ING_PERCAPITA_HOGAR), !is.na(condic_activi), !is.na(Cap_grado)) %>% 
  group_by(condic_activi, Cap_grado) %>%  summarise(
    Promedio_Ingreso = mean(ING_PERCAPITA_HOGAR, na.rm = TRUE),
    .groups = "drop") %>% 
  pivot_wider(
    names_from = Cap_grado,
    values_from = Promedio_Ingreso
  ) %>% mutate_if(is.numeric, ~ round(.x, 0))

```


```{r}
kable(cuadro_pos_trab_vs_grad_disc, caption = "Distribución porcentual de la posición en el trabajo según el grado de dificultad en la capacidad")
kable(cuadro_condic_actividad_vs_grad_disc, caption = "Distribución porcentual de la condición de actividad laboral según grado de dificultad en la capacidad")
kable(cuadro_discapacidad_region_zona, caption = "Distribución de personas con discapacidad por región y zona de residencia")
kable(cuadro_ingreso_vs_grado_discap, caption = "Distribución porcentual del ingreso per cápita por grado de discapacidad")
kable(cuadro_enfermedades_vs_grado_discap, caption = "Distribución de enfermedades crónicas por grado de discapacidad")
kable(cuadro_productos_vs_grado_discap, caption = "Necesidad de productos de apoyo según grado de discapacidad")
kable(cuadro_frec_relativa_pos_grado, caption = "Frecuencia relativa de la posición en el trabajo según grado de capacidad")
kable(cuadro_promedio_ingreso_vs_pos_y_grado, caption = "Promedio del ingreso per cápita del hogar según condición de actividad y grado de discapacidad")

```

