{
  "hash": "74b10891f2bc007b4e44a7aa38815c9f",
  "result": {
    "engine": "knitr",
    "markdown": "# Bitácora 2\n\n## Nuevas fichas de literatura\n\n::: {.callout-note }\n\n#### Estudio sobre el agravio comparativo económico que origina la discapacidad\n\n- **Título:** Estudio sobre el agravio comparativo económico que origina la discapacidad\n- **Autores:** Antonio Jiménez Lara y Agustín Huete García\n- **Año de publicación:** 2010\n- **Tema principal:** Impacto económico de la discapacidad en España\n- **Forma de organizarlo:**\n    - **Cronológico:** Basado en datos de la Encuesta EDAD 2008.\n    - **Metodológico:** Análisis de datos estadísticos y trabajo de campo cualitativo.\n    - **Temático:** Discapacidad, Economía.\n    - **Teórico:** Teoría de la discriminación económica y del sobrecoste asociado a la discapacidad.\n- **Resumen en una oración:** El estudio cuantifica los costes directos y de oportunidad que enfrentan las personas con discapacidad y sus hogares en España.\n- **Argumento central:** El documento plantea que las personas con discapacidad sufren un agravio económico relevante, expresado tanto en gastos monetarios adicionales como en pérdida de ingresos, exacerbado por la insuficiencia de apoyos estatales y la desigualdad en el acceso a recursos básicos.\n- **Posibles problemas con el argumento o tema:** El estudio reconoce la dificultad de captar la totalidad del impacto económico real debido a la falta de datos precisos y la subestimación del gasto y de las pérdidas de ingresos en las fuentes utilizadas.\n- **Resumen en un párrafo:** Los autores analizan cómo la discapacidad genera un agravio económico en los hogares españoles, señalando que las personas con discapacidad afrontan gastos directos significativos, como un gasto medio anual de 2.874 euros por hogar, lo que representa el 9% del gasto promedio anual en el país. Además, los hogares afectados perciben un 25% menos de ingresos que aquellos sin discapacidad, equivalente a una pérdida anual de unos 20 mil millones de euros. Se estima que el coste de oportunidad asociado al cuidado familiar no remunerado alcanza los 87 mil millones de euros, aproximadamente el 7% del PIB. \n\n:::\n\n::: {.callout-note }\n\n#### Dead End Jobs or a Path to Economic Well Being? The Consequences of Non-Standard Work among People with Disabilities\n\n- **Título:** Dead End Jobs or a Path to Economic Well Being? The Consequences of Non-Standard Work among People with Disabilities\n- **Autores:** Lisa A. Schur\n- **Año de publicación:** 2002\n- **Tema principal:** Impacto del empleo no tradicional en la situación económica de personas con discapacidad\n- **Forma de organizarlo:**\n    - **Cronológico:** Basado en datos recolectados entre 1992 y 2001.\n    - **Metodológico:** Uso de encuestas nacionales y revisión de casos legales.\n    - **Temático:** Empleo, Discapacidad.\n    - **Teórico:** Desigualdad económica asociada al tipo de empleo y la discapacidad.\n- **Resumen en una oración:** El estudio analiza cómo los trabajos no convencionales afectan la estabilidad económica de las personas con discapacidad.\n- **Argumento central:** El documento plantea que las personas con discapacidad están más presentes en empleos no tradicionales, donde ganan menos, reciben menos beneficios y tienen más probabilidades de vivir en pobreza, afectando sus posibilidades de mejorar su situación económica.\n- **Posibles problemas con el argumento o tema:** Se mencionan limitaciones en la calidad de los datos, posibles errores al medir la discapacidad y complicaciones al usar los resultados de demandas judiciales como forma de medir mejoras laborales.\n- **Resumen en un párrafo:** Los autores explican que las personas con discapacidad en Estados Unidos suelen trabajar en empleos de medio tiempo, temporales o como independientes mucho más que las personas sin discapacidad. Indican que un 44% de trabajadores con discapacidad está en este tipo de empleos, mientras que solo un 22% de personas sin discapacidad lo está. También se menciona que estos trabajadores ganan entre un 14% y un 22% menos y que aproximadamente un 20% vive en pobreza, lo que es el doble comparado con personas sin discapacidad en trabajos parecidos. El estudio, usando encuestas y revisiones de casos legales, muestra que solo un 25% de las demandas laborales de personas con discapacidad tienen éxito. \n\n:::\n\n::: {.callout-note }\n\n#### Inequality in Labour Market Opportunities for People with Disabilities: Evidence for Six Latin American Countries\n\n- **Título:** Inequality in Labour Market Opportunities for People with Disabilities: Evidence for Six Latin American Countries\n- **Autores:** Mónica Pinilla-Roncancio y Mauricio Gallardo\n- **Año de publicación:** 2023\n- **Tema principal:** Desigualdad en las oportunidades laborales de personas con discapacidad en seis países latinoamericanos\n- **Forma de organizarlo:**\n    - **Cronológico:** Basado en encuestas de hogares hechas entre 2016 y 2017.\n    - **Metodológico:** Se utilizó el Índice de Oportunidades Humanas (HOI) junto con datos de encuestas.\n    - **Temático:** Empleo, Discapacidad.\n    - **Teórico:** Teoría de equidad de oportunidades en el ámbito laboral.\n- **Resumen en una oración:** Este estudio analiza las diferencias en las oportunidades laborales para personas con discapacidad en seis países de América Latina.\n- **Argumento central:** El estudio dice que las personas con discapacidad tienen muchas más dificultades para conseguir empleo en América Latina, y que esto cambia bastante dependiendo del país, siendo peor para las mujeres y quienes viven en zonas rurales.\n- **Posibles problemas con el argumento o tema:** Se mencionan problemas porque los datos no siempre son fáciles de comparar entre los países, y eso puede afectar los resultados.\n- **Resumen en un párrafo:** Los autores estudian cómo es la situación laboral para personas con discapacidad en Bolivia, Chile, Colombia, Costa Rica, México y Perú. Usaron encuestas y el Índice de Oportunidades Humanas para ver las diferencias. Encontraron que en todos los países las personas con discapacidad tienen menos chances de trabajar, pero especialmente en Costa Rica y Colombia, donde las oportunidades laborales bajan más de un 30%. En cambio, en Perú más del 80% de las personas con discapacidad tienen acceso al empleo, aunque con diferencias internas. Además, ser mujer o vivir en el campo reduce todavía más la posibilidad de conseguir trabajo. Un dato importante es que en Colombia las personas con discapacidad tienen un 98% menos de probabilidad de estar empleadas.\n\n:::\n\n::: {.callout-note }\n\n#### The Disability Employment Puzzle: A Field Experiment on Employer Hiring Behavior\n\n- **Título:** The Disability Employment Puzzle: A Field Experiment on Employer Hiring Behavior\n- **Autores:** Mason Ameri, Lisa Schur, Meera Adya, Scott Bentley, Patrick McKay y Douglas Kruse\n- **Año de publicación:** 2015\n- **Tema principal:** Discriminación laboral hacia personas con discapacidad en procesos de contratación\n- **Forma de organizarlo:**\n    - **Cronológico:** Datos recogidos entre junio y agosto de 2013.\n    - **Metodológico:** Experimento de campo enviando solicitudes ficticias a ofertas de empleo.\n    - **Temático:** Discriminación, Empleo, Discapacidad.\n    - **Teórico:** Teoría de la discriminación y del capital humano.\n- **Resumen en una oración:** Este estudio investiga si las personas con discapacidad enfrentan discriminación a la hora de buscar empleo en Estados Unidos.\n- **Argumento central:** El estudio muestra que las personas con discapacidad, a pesar de tener buenas calificaciones, reciben mucho menos interés de los empleadores que las personas sin discapacidad.\n- **Posibles problemas con el argumento o tema:** Se reconoce que tal vez no todos los empleadores leyeron las cartas de presentación donde se hablaba de la discapacidad, lo que podría hacer que el problema parezca más pequeño de lo que realmente es.\n- **Resumen en un párrafo:** Los autores hicieron un experimento enviando más de 6,000 solicitudes de trabajo a ofertas en el área de contabilidad. Unas solicitudes mencionaban una discapacidad (lesión medular o Asperger) y otras no. Encontraron que las personas con discapacidad recibieron 26% menos respuestas de interés que quienes no mencionaban discapacidad. Además, se vio que la diferencia era mayor para quienes tenían más experiencia laboral y que las pequeñas empresas (con menos de 15 empleados) eran las que menos respondían.  \n\n:::\n\n::: {.callout-note }\n\n#### Income and Employment Equity of Graduates with and without Disabilities\n\n- **Título:** Income and Employment Equity of Graduates with and without Disabilities\n- **Autores:** Michelle Donelly, Scott Gordon y Alison Bowling\n- **Año de publicación:** 2020\n- **Tema principal:** Desigualdad de ingresos y empleo entre graduados con y sin discapacidad en Australia\n- **Forma de organizarlo:**\n    - **Cronológico:** Basado en datos del Censo Australiano de 2011.\n    - **Metodológico:** Análisis descriptivo y de regresión de datos censales.\n    - **Temático:** Empleo, Discapacidad, Economía.\n    - **Teórico:** Teoría de equidad de ingresos y empleo.\n- **Resumen en una oración:** El estudio analiza las diferencias de ingresos y empleo entre graduados con y sin discapacidad en Australia.\n- **Argumento central:** El estudio muestra que los graduados con discapacidad ganan mucho menos, trabajan menos horas y tienen trayectorias laborales más inestables que los graduados sin discapacidad, con diferencias aún más marcadas por género.\n- **Posibles problemas con el argumento o tema:** Se reconocen limitaciones en la definición de discapacidad usada en el censo y posibles sesgos en la información recolectada.\n- **Resumen en un párrafo:** Los autores analizaron datos del Censo Australiano de 2011 para comparar los ingresos de graduados con y sin discapacidad. Encontraron que los graduados con discapacidad ganaban en promedio $494 AUD por semana, lo que equivale al 53% de los ingresos de quienes no tenían discapacidad. Además, trabajaban menos horas (20.6 horas semanales frente a 31.2 horas) y recibían un salario por hora 15% más bajo. Las mujeres con discapacidad fueron el grupo con menores ingresos, ganando apenas un 35% de lo que ganaban los hombres sin discapacidad. El estudio también mostró que las diferencias de ingreso aumentaban con la edad y que, aunque la indigeneidad fue un factor de inequidad en general, entre mujeres graduadas no se observaron diferencias significativas. \n\n:::\n\n::: {.callout-note }\n\n#### A Study on the Employment and Wage Outcomes of People with Disabilities\n\n- **Título:** A Study on the Employment and Wage Outcomes of People with Disabilities\n- **Autores:** Sévane Ananian y Giulia Dellaferrera\n- **Año de publicación:** 2024\n- **Tema principal:** Resultados laborales y salariales de personas con discapacidad a nivel internacional\n- **Forma de organizarlo:**\n    - **Cronológico:** Basado en encuestas de hogares realizadas entre 2013 y 2022.\n    - **Metodológico:** Análisis econométrico de datos censales de 65 países.\n    - **Temático:** Economía, Discapacidad.\n    - **Teórico:** Teoría de discriminación y equidad de oportunidades laborales.\n- **Resumen en una oración:** El estudio analiza las diferencias de empleo y salarios entre personas con y sin discapacidad en varios países.\n- **Argumento central:** El estudio demuestra que las personas con discapacidad tienen menos posibilidades de participar en el mercado laboral, enfrentan mayores tasas de desempleo y ganan menos que quienes no tienen discapacidad, incluso cuando tienen niveles similares de educación y experiencia.\n- **Posibles problemas con el argumento o tema:** Se reconoce que las diferencias entre países y la forma de medir la discapacidad pueden afectar los resultados, así como la falta de datos sobre discapacidades menos visibles.\n- **Resumen en un párrafo:** Los autores analizaron datos de 65 países para comparar los resultados laborales de personas con y sin discapacidad. Encontraron que tener discapacidad disminuye en promedio en 25% la probabilidad de participar en el mercado laboral y aumenta en 7% la probabilidad de estar desempleado. Además, las personas con discapacidad ganan un 12% menos por hora que las personas sin discapacidad, y tres cuartas partes de esa brecha salarial no se explican por diferencias de edad, educación u ocupación. El estudio también muestra que en países de ingresos bajos y medianos, las personas con discapacidad tienen tasas de informalidad y trabajo temporal mucho más altas.\n\n:::\n\n::: {.callout-note }\n\n#### Multinomial Logistic Regression to Estimate and Predict the Job Opportunities for People with Disabilities in Chile\n\n- **Título:** Multinomial Logistic Regression to Estimate and Predict the Job Opportunities for People with Disabilities in Chile\n- **Autores:** Nelson Lay-Raby, Hanns de la Fuente-Mella y Omar Lameles-Corvalán\n- **Año de publicación:** 2021\n- **Tema principal:** Predicción de oportunidades laborales para personas con discapacidad en Chile\n- **Forma de organizarlo:**\n    - **Cronológico:** Basado en datos del Segundo Estudio Nacional de Discapacidad en Chile (ENDISC II) de 2015.\n    - **Metodológico:** Modelo de regresión logística multinomial aplicado a una muestra de 1,566 adultos.\n    - **Temático:** Empleo, Discapacidad.\n    - **Teórico:** Modelo social de la discapacidad y teoría económica del empleo.\n- **Resumen en una oración:** Este estudio analiza cómo diferentes factores influyen en las oportunidades de empleo de personas con discapacidad en Chile.\n- **Argumento central:** El estudio muestra que factores como el nivel educativo, los ingresos autónomos, la edad y los subsidios del Estado afectan de manera importante las probabilidades de que una persona con discapacidad consiga trabajo en Chile.\n- **Posibles problemas con el argumento o tema:** Se reconoce que la muestra solo incluye a personas hasta 30 años y que algunos factores sociales o de contexto podrían no estar completamente reflejados en el análisis.\n- **Resumen en un párrafo:** Los autores utilizaron datos del Segundo Estudio Nacional de Discapacidad en Chile para construir un modelo de regresión logística multinomial que permitiera predecir las oportunidades laborales de personas con discapacidad. La muestra incluyó a 1,566 personas adultas entre 18 y 30 años, y se analizaron variables como ingresos autónomos, pensiones, subsidios mensuales y anuales, edad, estado civil, y último nivel educativo alcanzado. Se encontró que tener un nivel educativo más alto y recibir ingresos propios aumentaba de manera considerable la probabilidad de empleo. Las personas con discapacidad severa tenían menos posibilidades de insertarse laboralmente, y el acceso a subsidios mensuales también mostraba una relación importante. El modelo tuvo un buen ajuste, logrando clasificar correctamente el 92.3% de los casos.\n\n:::\n\n::: {.callout-note }\n\n#### Effects of Disability on Income and Income Composition\n\n- **Título:** Effects of Disability on Income and Income Composition\n- **Autores:** Christy Pu y Huei-Fen Syu\n- **Año de publicación:** 2023\n- **Tema principal:** Efectos de la discapacidad sobre el ingreso y su composición en Taiwán\n- **Forma de organizarlo:**\n    - **Cronológico:** Basado en datos fiscales de 1999 a 2015.\n    - **Metodológico:** Uso de datos administrativos y análisis estadístico de ingresos.\n    - **Temático:** Economía, Discapacidad.\n    - **Teórico:** Teoría de composición del ingreso y desigualdad económica.\n- **Resumen en una oración:** El estudio analiza cómo la discapacidad afecta el ingreso total y la composición de los tipos de ingreso en Taiwán.\n- **Argumento central:** El estudio muestra que tras el inicio de una discapacidad, el ingreso total no disminuye en general, pero la composición del ingreso cambia de manera importante, con diferencias según la edad y el tipo de ingreso.\n- **Posibles problemas con el argumento o tema:** Se reconoce que los datos incluyen solo hogares con ingresos tributables y que no se pueden distinguir tipos ni severidades de discapacidad.\n- **Resumen en un párrafo:** Los autores analizaron datos fiscales de Taiwán para comparar los cambios en el ingreso de personas con discapacidad y personas sin discapacidad. Encontraron que, en promedio, el ingreso total aumentó un 10.4% tras el inicio de la discapacidad, y que los salarios no disminuyeron de manera significativa. Sin embargo, la composición de los ingresos cambió, destacándose un aumento en los ingresos por intereses y transacciones de propiedades. Antes de los 50 años, las personas con discapacidad tenían una mayor proporción de ingresos por intereses, pero después de esa edad, esta proporción era mayor en personas sin discapacidad. También se observó que la proporción de ingresos por salarios disminuía conforme aumentaba la edad.\n\n:::\n\n::: {.callout-note }\n\n#### More than just lower wages: intrinsic job quality for college graduates with disabilities\n\n- **Título:** More than just lower wages: intrinsic job quality for college graduates with disabilities\n- **Autores:** Megan Henly y Debra L. Brucker\n- **Año de publicación:** 2020\n- **Tema principal:** Calidad intrínseca del trabajo para graduados universitarios con discapacidad\n- **Forma de organizarlo:**\n    - **Cronológico:** Basado en datos de la Encuesta Nacional de Graduados Universitarios de 2017.\n    - **Metodológico:** Análisis de datos de encuesta y modelación de calidad de empleo.\n    - **Temático:** Educación, Empleo, Discapacidad.\n    - **Teórico:** Teoría de calidad del trabajo y desigualdad laboral.\n- **Resumen en una oración:** El estudio analiza las diferencias en salarios y calidad intrínseca del trabajo entre graduados universitarios con y sin discapacidad en Estados Unidos.\n- **Argumento central:** El estudio plantea que los graduados universitarios con discapacidad reciben menores salarios y disfrutan de menor calidad intrínseca en el trabajo en comparación con sus pares sin discapacidad.\n- **Posibles problemas con el argumento o tema:** Se señala que las medidas usadas para evaluar la calidad intrínseca son subjetivas y podrían no captar todas las dimensiones relevantes del trabajo.\n- **Resumen en un párrafo:** Los autores analizaron datos de una encuesta nacional de graduados universitarios para comparar la calidad del empleo entre personas con y sin discapacidad. Encontraron que los trabajadores con discapacidad ganaban un salario medio de \\$63,600 USD, mientras que los trabajadores sin discapacidad ganaban \\$70,000 USD. Además, aunque ambos grupos valoraban mucho aspectos como la autonomía y la realización personal, las personas con discapacidad reportaban niveles significativamente más bajos en tres de los cuatro indicadores de calidad intrínseca del trabajo. En general, solo el 63% de los trabajadores con discapacidad estaba satisfecho en todas las dimensiones analizadas, frente al 70% de los trabajadores sin discapacidad. Finalmente, el estudio mostró que tener una discapacidad redujo en 29% las probabilidades de tener un empleo considerado de alta calidad intrínseca.\n\n:::\n\n::: {.callout-note }\n\n#### Informe Mundial sobre la Discapacidad\n\n- **Título:** Informe Mundial sobre la Discapacidad\n- **Autores:** Organización Mundial de la Salud (OMS) y Banco Mundial\n- **Año de publicación:** 2011\n- **Tema principal:** Discapacidad, Salud, Educación, Empleo\n- **Forma de organizarlo:**\n    - **Cronológico:** Datos y análisis recopilados hasta 2010.\n    - **Metodológico:** Revisión de literatura, análisis de encuestas internacionales y consultas regionales.\n    - **Temático:** Discapacidad, Salud, Educación, Empleo.\n    - **Teórico:** Modelo biopsicosocial de la discapacidad.\n- **Resumen en una oración:** El informe analiza la situación mundial de las personas con discapacidad y propone acciones para mejorar su inclusión social.\n- **Argumento central:** El informe muestra que más de mil millones de personas viven con algún tipo de discapacidad y enfrentan barreras significativas en salud, educación, empleo y participación social.\n- **Posibles problemas con el argumento o tema:** Se reconoce que la falta de datos comparables y de definiciones comunes limita el conocimiento sobre la situación de la discapacidad a nivel mundial.\n- **Resumen en un párrafo:** Los autores presentan un diagnóstico global basado en datos de encuestas y revisiones de literatura sobre la vida de las personas con discapacidad. Se estima que el 15% de la población mundial vive con alguna forma de discapacidad, y que cerca de 200 millones experimentan dificultades considerables en su funcionamiento. El informe destaca que estas personas tienen peores resultados en salud, educación y empleo, y mayores tasas de pobreza que el resto de la población. Además, identifica barreras ambientales, actitudinales y legales que afectan su participación social. Se abordan temas como la accesibilidad, la rehabilitación, la asistencia personal y la necesidad de ambientes inclusivos, basándose en el modelo de la Clasificación Internacional del Funcionamiento, la Discapacidad y la Salud (CIF). Cada capítulo ofrece recomendaciones específicas para gobiernos y actores sociales con el fin de promover la equidad y los derechos de las personas con discapacidad.\n\n:::\n\n::: {.callout-note}\n\n#### The Chi-square Test of Independence\n\n- **Título:** The Chi-square Test of Independence  \n- **Autores:** Mary L. McHugh  \n- **Año de publicación:** 2013  \n- **Tema principal:** Prueba de independencia Chi-cuadrado en datos categóricos  \n- **Forma de organizarlo:**\n    - **Cronológico:** Aplicación contemporánea en estudios con variables cualitativas.  \n    - **Metodológico:** Uso de estadística no paramétrica.  \n    - **Temático:** Estadística.  \n    - **Teórico:** Análisis de hipótesis con variables categóricas.  \n- **Resumen en una oración:** El artículo explica cómo usar la prueba Chi-cuadrado para analizar si dos variables están relacionadas.  \n- **Argumento central:** La autora presenta la prueba Chi-cuadrado como una herramienta útil para saber si hay relación entre variables categóricas, sobre todo cuando no se pueden usar pruebas paramétricas más comunes.  \n- **Posibles problemas con el argumento o tema:** La prueba necesita ciertos requisitos, como que las muestras no sean pequeñas y que los datos estén bien organizados; si no se cumplen, los resultados pueden no ser fiables.  \n- **Resumen en un párrafo:** Este artículo describe qué es y para qué sirve la prueba Chi-cuadrado de independencia. Se usa cuando las variables que se quieren comparar están en categorías, por ejemplo, si una persona está vacunada o no, y si se enfermó o no. La autora explica que esta prueba no necesita que los datos sigan una distribución normal, lo cual es útil cuando no se pueden aplicar otras pruebas estadísticas. A través de un ejemplo sobre vacunación y tipos de neumonía, se muestran los pasos para calcular los valores esperados y determinar si las diferencias encontradas son significativas. También se habla de otra medida, el V de Cramér, que sirve para saber qué tan fuerte es la relación entre las variables. Al final, se compara esta prueba con otras parecidas, explicando cuándo es mejor usar una u otra.\n\n:::\n\n::: {.callout-note}\n\n#### Methodology and Application of the Kruskal-Wallis Test\n\n- **Título:** Methodology and Application of the Kruskal-Wallis Test  \n- **Autores:** Eva Ostertagová, Oskar Ostertag y Jozef Kováč  \n- **Año de publicación:** 2014  \n- **Tema principal:** Prueba no paramétrica Kruskal-Wallis y su aplicación práctica  \n- **Forma de organizarlo:**\n    - **Cronológico:** Se basa en datos y métodos recientes  \n    - **Metodológico:** Uso de la prueba Kruskal-Wallis con análisis comparativo entre grupos  \n    - **Temático:** Estadística  \n    - **Teórico:** Comparación de grupos usando rangos en lugar de promedios  \n- **Resumen en una oración:**  \n  El texto explica cómo funciona la prueba Kruskal-Wallis y cuándo conviene usarla si los datos no cumplen los requisitos de una prueba común como el ANOVA.  \n- **Argumento central:**  \n  La prueba Kruskal-Wallis es útil para comparar tres o más grupos cuando los datos no son normales ni tienen varianzas similares, permitiendo saber si hay diferencias importantes entre ellos.  \n- **Posibles problemas con el argumento o tema:**  \n  Aunque no exige tantos requisitos como otras pruebas, necesita que los grupos sean independientes y parecidos en forma; además, si el resultado da diferencia, no muestra claramente entre qué grupos ocurre, así que hay que hacer comparaciones por separado.  \n- **Resumen en un párrafo:**  \n  Este artículo presenta la prueba Kruskal-Wallis como una forma de comparar varios grupos cuando los datos no permiten usar pruebas más comunes como el ANOVA. Explica paso a paso cómo se realiza el cálculo, qué condiciones debe cumplir y qué hacer si hay valores repetidos. Incluye un ejemplo con datos reales sobre el efecto de cinco tipos de recubrimiento en tubos, usando MATLAB para el análisis. Como los datos no cumplían con las condiciones necesarias para un análisis normal, se usó esta prueba y se encontró que al menos uno de los grupos era diferente. Para saber cuáles eran distintos, se hicieron comparaciones entre pares de grupos.\n\n:::\n\n\n## Parte de planificación\n\n### Ordenamiento de la literatura\n\n> **Nota:** Todas las referencias incluidas en la siguiente tabla corresponden a estudios de tipo **temático**, es decir, se agrupan por temas relevantes para el análisis del vínculo entre discapacidad y condiciones socioeconómicas.\n\n| **Tema general**                            | **Tema específico**                                                 | **Título**                                                                 | **Año** | **Autor(es)**                                                                                      |\n|---------------------------------------------|----------------------------------------------------------------------|-----------------------------------------------------------------------------|--------|----------------------------------------------------------------------------------------------------|\n| Discapacidad, Salud, Educación, Empleo       | Situación mundial sobre discapacidad                                 | Informe Mundial sobre la Discapacidad                                       | 2011   | OMS y Banco Mundial                                                                                 |\n| Discapacidad, Economía                       | Impacto económico de la discapacidad                                 | Estudio sobre el agravio comparativo que origina la discapacidad            | 2010   | Antonio Jiménez Lara y Agustín Huete García                                                         |\n| Economía, Discapacidad                       | Resultados laborales internacionales                                 | A Study on the Employment and Wage Outcomes of People with Disabilities     | 2024   | Sévane Ananian y Giulia Dellaferrera                                                               |\n| Educación, Economía, Discapacidad            | Desigualdad de ingresos entre graduados                              | Income and Employment Equity of Graduates with and without Disabilities     | 2020   | Michelle Donelly, Scott Gordon y Alison Bowling                                                    |\n| Empleo, Discapacidad                         | Oportunidades laborales en América Latina                            | Inequality in Labour Market Opportunities for People with Disabilities      | 2023   | Mónica Pinilla-Roncancio y Mauricio Gallardo                                                       |\n| Empleo, Discapacidad                         | Empleo no tradicional                                                | Dead End Jobs or a Path to Economic Well Being?                             | 2002   | Lisa A. Schur                                                                                       |\n| Discapacidad, Economía, Empleo               | Disparidades laborales entre personas con discapacidad               | Disability at Work: A Look Back and Forward                                 | 2017   | Lisa Schur, Kyongji Han, Andrea Kim, Mason Ameri, Peter Blanck, Douglas Kruse                      |\n| Discriminación, Empleo, Discapacidad         | Discriminación en contratación laboral                               | The Disability Employment Puzzle                                            | 2015   | Mason Ameri, Lisa Schur, Meera Adya, Scott Bentley, Patrick McKay y Douglas Kruse                  |\n| Educación, Empleo, Discapacidad              | Calidad intrínseca del empleo                                        | More than just lower wages: intrinsic job quality for college graduates... | 2020   | Megan Henly y Debra L. Brucker                                                                      |\n| Discapacidad, Empleo, Políticas Públicas     | Inclusión laboral en Costa Rica                                      | Retos para la inclusión laboral de personas con discapacidad en Costa Rica | 2020   | Héctor Andrés Canossa Montes de Oca                                                                 |\n| Empleo, Discapacidad                         | Predicción de empleo en Chile                                        | Multinomial Logistic Regression to Estimate and Predict the Job Opportunities | 2021   | Nelson Lay-Raby, Hanns de la Fuente-Mella y Omar Lameles-Corvalán                                  |\n\n\n### Enlaces de la literatura\n\n**Informe Mundial sobre la Discapacidad – OMS y Banco Mundial (2011)**\n\n**Resumen:**  \nEste informe habla sobre cómo viven las personas con discapacidad en todo el mundo. Explica que hay más de mil millones de personas en esta condición y que se enfrentan a muchos obstáculos en temas como salud, educación, trabajo y participación social. También señala que es importante que los gobiernos hagan políticas que respeten sus derechos para mejorar su inclusión.\n\n**Contraste:**  \nEl informe da una visión general de la situación en todo el mundo, a diferencia de otros estudios que son más específicos y que hablan sobre problemas concretos como el empleo o el dinero que ganan las personas con discapacidad en ciertos países o regiones.\n\n**Contribución propia:**  \nAunque este informe ayuda mucho a entender la situación de manera global, también deja claro que es necesario tener estudios más locales que expliquen mejor qué pasa en cada país. Así se pueden hacer políticas que se adapten mejor a cada realidad y no quedarse solo con una visión muy amplia.\n\n**Estudio sobre el agravio comparativo económico que origina la discapacidad – Antonio Jiménez Lara y Agustín Huete García (2010)**\n\n**Resumen:**  \nEste estudio analiza cómo la discapacidad afecta la economía de las personas y sus familias en España. Encontraron que quienes tienen discapacidad gastan más dinero en su vida diaria y además ganan menos ingresos que las personas sin discapacidad. También se habla de cómo el apoyo que da el Estado no alcanza para cubrir esas diferencias.\n\n**Contraste:**  \nA diferencia del Informe Mundial sobre la Discapacidad, que da una idea general del problema a nivel mundial, este estudio se enfoca en un país en específico y da cifras claras sobre cuánto afecta económicamente vivir con una discapacidad. Mientras uno presenta el panorama grande, este otro aterriza el problema en la vida diaria de las personas en España.\n\n**Contribución propia:**  \nEstudios como este son importantes porque ayudan a entender que las barreras no son solo sociales o de participación, sino que también tienen un impacto directo en el bolsillo de las personas. Tener datos concretos permite que se hagan políticas públicas más realistas y no solo basadas en buenas intenciones.\n\n**Effects of Disability on Income and Income Composition – Christy Pu y Huei-Fen Syu (2023)**\n\n**Resumen:**  \nEste estudio analiza qué pasa con los ingresos de las personas cuando adquieren una discapacidad en Taiwán. Encontraron que, aunque el ingreso total no baja mucho, sí cambia la forma en la que las personas obtienen su dinero. Por ejemplo, ganan menos por salario y dependen más de intereses o transacciones de propiedades, sobre todo conforme van envejeciendo.\n\n**Contraste:**  \nAl igual que el estudio en España, este trabajo se enfoca en cómo la discapacidad tiene un efecto económico real. Sin embargo, mientras en España se veía una caída clara en los ingresos, aquí el ingreso total no baja tanto, pero sí cambia la composición de esos ingresos. Esto muestra que el impacto económico no siempre se ve igual en todos los países o contextos.\n\n**Contribución propia:**  \nEste tipo de estudios ayuda a ver que el problema económico de la discapacidad no solo es ganar menos dinero, sino también depender de otros tipos de ingresos que pueden ser menos estables. Entender estos matices es clave para diseñar apoyos económicos que realmente sirvan a las personas según su situación.\n\n**A Study on the Employment and Wage Outcomes of People with Disabilities – Sévane Ananian y Giulia Dellaferrera (2024)**\n\n**Resumen:**  \nEste estudio compara a nivel internacional las diferencias en empleo y salarios entre personas con y sin discapacidad. Los autores encontraron que las personas con discapacidad tienen menos posibilidades de estar empleadas y, cuando trabajan, suelen ganar menos dinero, aunque tengan niveles de educación y experiencia parecidos a los de personas sin discapacidad.\n\n**Contraste:**  \nEste trabajo refuerza lo que otros estudios han señalado sobre los efectos económicos de la discapacidad, pero en lugar de enfocarse en un solo país, aquí se muestra cómo el problema es común en muchos países, especialmente en los de ingresos bajos y medios. Así se ve que las barreras no son solo un problema local, sino algo que pasa en todo el mundo.\n\n**Contribución propia:**  \nEl estudio deja claro que aunque existan políticas de inclusión en muchos lugares, las personas con discapacidad siguen enfrentando dificultades grandes para conseguir y mantener trabajos bien pagados. Tener evidencia internacional ayuda a entender que se necesitan cambios más profundos y no solo esfuerzos aislados en ciertos países.\n\n**Income and Employment Equity of Graduates with and without Disabilities – Michelle Donelly, Scott Gordon y Alison Bowling (2020)**\n\n**Resumen:**  \nEste estudio analiza cómo les va en el empleo y en los ingresos a los graduados universitarios en Australia, comparando a quienes tienen discapacidad con quienes no la tienen. Los resultados muestran que los graduados con discapacidad ganan mucho menos, trabajan menos horas y tienen trayectorias laborales más inestables, siendo las mujeres con discapacidad las más afectadas.\n\n**Contraste:**  \nAl igual que los estudios anteriores que mostraban desventajas laborales para personas con discapacidad, este trabajo confirma que ni siquiera tener educación superior garantiza igualdad en el mercado laboral. Mientras en otros estudios se habla en general del empleo, aquí se ve que la inequidad persiste incluso entre quienes han logrado graduarse de la universidad.\n\n**Contribución propia:**  \nEste tipo de hallazgos es importante porque rompe con la idea de que solo falta educación para solucionar la desigualdad laboral. La discriminación o las barreras estructurales siguen afectando a las personas con discapacidad, aunque tengan títulos universitarios, lo que muestra que el problema es más complejo.\n\n**Inequality in Labour Market Opportunities for People with Disabilities – Mónica Pinilla-Roncancio y Mauricio Gallardo (2023)**\n\n**Resumen:**  \nEste estudio analiza las oportunidades laborales de las personas con discapacidad en seis países de América Latina. Los resultados muestran que, en todos los países, las personas con discapacidad tienen muchas menos posibilidades de conseguir empleo, pero la situación varía bastante entre un país y otro. También se encontró que las mujeres y las personas que viven en zonas rurales enfrentan todavía más dificultades.\n\n**Contraste:**  \nEste trabajo complementa lo que otros estudios internacionales han mostrado, pero se enfoca en una región específica como América Latina. Mientras que algunos trabajos anteriores se centraban en diferencias de ingresos, aquí se pone más atención en las oportunidades de acceso al trabajo, lo que ayuda a entender otra dimensión del problema.\n\n**Contribución propia:**  \nEste tipo de estudios es clave porque muestra que no todos los países tienen las mismas barreras, y que hay factores como el género o el lugar donde se vive que complican aún más el acceso al empleo. Entender estas diferencias internas ayuda a que las políticas de inclusión sean más específicas y no iguales para todos.\n\n**Dead End Jobs or a Path to Economic Well Being? – Lisa A. Schur (2002)**\n\n**Resumen:**  \nEste estudio analiza cómo afectan los trabajos de medio tiempo, temporales o independientes a las personas con discapacidad en Estados Unidos. La autora encontró que las personas con discapacidad tienen más probabilidades de estar en este tipo de empleos, que generalmente son peor pagados y ofrecen menos beneficios, lo cual aumenta el riesgo de vivir en pobreza.\n\n**Contraste:**  \nEste trabajo se conecta bien con los estudios anteriores que hablan de las barreras laborales, pero aquí se pone el foco en el tipo de empleo que logran conseguir las personas con discapacidad. Mientras otros estudios hablan más de si logran o no conseguir trabajo, este muestra que muchas veces sí consiguen trabajo, pero en condiciones mucho peores que el resto.\n\n**Contribución propia:**  \nEste enfoque es importante porque demuestra que no basta con decir que una persona con discapacidad tiene empleo; también hay que ver la calidad de ese trabajo. Tener un empleo de baja calidad puede seguir dejando a las personas en situaciones de vulnerabilidad económica.\n\n**Disability at Work: A Look Back and Forward – Lisa Schur et al. (2017)**\n\n**Resumen:**  \nEste estudio analiza las desventajas laborales que enfrentan las personas con discapacidad en términos de estabilidad, salarios y acceso a beneficios. También discute las razones detrás de estas diferencias, explicando que pueden deberse tanto a discriminación directa como a decisiones personales que las personas toman buscando flexibilidad laboral.\n\n**Contraste:**  \nEste trabajo conecta con los estudios anteriores que muestran las desventajas en el mercado laboral, pero agrega algo más: introduce la idea de que no todo es discriminación, sino que en algunos casos las personas con discapacidad aceptan condiciones diferentes para poder tener más flexibilidad. Esto hace que el análisis del problema sea un poco más matizado.\n\n**Contribución propia:**  \nEs importante reconocer que no todo puede explicarse solo por barreras externas. A veces las personas con discapacidad también toman decisiones estratégicas sobre su empleo. Ver el tema desde varios ángulos ayuda a no simplificar demasiado un problema que en realidad es bastante complejo.\n\n**The Disability Employment Puzzle – Mason Ameri et al. (2015)**\n\n**Resumen:**  \nEste estudio hizo un experimento en Estados Unidos para ver si las personas con discapacidad reciben menos interés de los empleadores al buscar trabajo. Enviaron miles de solicitudes ficticias y encontraron que las personas que mencionaban tener una discapacidad recibían menos respuestas positivas, a pesar de tener calificaciones similares a las de las personas sin discapacidad.\n\n**Contraste:**  \nEste trabajo complementa los estudios anteriores porque no solo muestra las desventajas en el empleo, sino que prueba de manera directa que la discriminación existe desde el momento en que las personas intentan entrar al mercado laboral. Mientras otros estudios hablaban de salarios o calidad del empleo, aquí se enfoca en el primer filtro: el proceso de contratación.\n\n**Contribución propia:**  \nEste tipo de investigaciones es muy valioso porque no depende solo de encuestas o percepciones, sino que demuestra con datos reales que la discriminación es un obstáculo real desde el inicio. Eso confirma que mejorar la inclusión laboral no solo depende de la persona con discapacidad, sino también de cambiar las actitudes de los empleadores.\n\n**More than just lower wages – Megan Henly y Debra L. Brucker (2020)**\n\n**Resumen:**  \nEste estudio analiza no solo cuánto ganan los graduados universitarios con discapacidad en Estados Unidos, sino también cómo es la calidad de sus trabajos. Encontraron que, además de ganar menos, estos trabajadores tienen empleos con menor autonomía, menos posibilidades de crecimiento y menos satisfacción personal comparado con los trabajadores sin discapacidad.\n\n**Contraste:**  \nA diferencia de otros estudios que se concentran en los salarios o en la posibilidad de tener un trabajo, este se enfoca en la calidad del empleo en sí. Aunque una persona con discapacidad logre conseguir un trabajo, eso no significa que sea un trabajo de buena calidad o que le permita crecer profesionalmente.\n\n**Contribución propia:**  \nEsto muestra que la inclusión laboral no debería medirse solo por la cantidad de personas empleadas, sino también por las condiciones en las que trabajan. No basta con tener un empleo; es necesario que ese empleo sea digno y que ofrezca posibilidades reales de desarrollo.\n\n**Retos para la inclusión laboral de personas con discapacidad en Costa Rica – Héctor Andrés Canossa Montes de Oca (2020)**\n\n**Resumen:**  \nEste estudio analiza las barreras que enfrentan las personas con discapacidad para entrar al mercado laboral en Costa Rica. A través de encuestas y entrevistas, se encontró que la mayoría de las empresas no contratan a personas con discapacidad por falta de accesibilidad, prejuicios o desconocimiento de los beneficios que ofrece el Estado.\n\n**Contraste:**  \nA diferencia de otros estudios más generales o internacionales, este trabajo se centra en el caso específico de Costa Rica, mostrando que, aunque existan leyes que promueven la inclusión, en la práctica las barreras siguen siendo muy fuertes. Confirma que los problemas que otros estudios mencionan también se repiten en el contexto costarricense.\n\n**Contribución propia:**  \nEste tipo de investigaciones locales es muy útil porque permite ver cómo los problemas de inclusión laboral no son solo un tema global, sino que también tienen raíces específicas en cada país.\n\n**Multinomial Logistic Regression to Estimate and Predict the Job Opportunities for People with Disabilities in Chile – Nelson Lay-Raby et al. (2021)**\n\n**Resumen:**  \nEste estudio usa un modelo estadístico para predecir las oportunidades de empleo de las personas con discapacidad en Chile. Analizando variables como el nivel educativo, los ingresos y los subsidios, encontraron que factores como tener más educación y contar con ingresos propios aumentan bastante las probabilidades de conseguir trabajo.\n\n**Contraste:**  \nMientras que otros estudios describen las barreras o los efectos de la discapacidad en el empleo, este aporta un enfoque más predictivo, usando datos para calcular qué tan probable es que una persona consiga un trabajo. Esto le da un valor diferente, porque no solo muestra el problema, sino que ayuda a identificar qué características ayudan a mejorar las oportunidades.\n\n**Contribución propia:**  \nTener estudios que no solo describan la situación, sino que también permitan hacer predicciones, es clave para entender mejor el problema. Saber qué factores hacen una diferencia permite enfocar los esfuerzos en áreas que realmente puedan mejorar las oportunidades laborales de las personas con discapacidad.\n\n\n\n\n\n{{< pagebreak >}}\n\n\n\n\n\n\n\n  \n## Análisis descriptivo\n\n\n\n\n\n\n\n\n\n\n\nPara este trabajo se utilizó la base de datos ENADIS 2023, que recoge información sobre personas con y sin discapacidad en Costa Rica. Se filtró la muestra para incluir únicamente a personas entre 18 y 65 años. Las variables analizadas en esta sección son: grado de discapacidad, zona y región de residencia, condición de actividad, posición en el trabajo, cantidad de horas trabajadas semanalmente e ingreso per cápita del hogar. A partir de estas variables, se generaron distintos gráficos y cuadros que permiten observar cómo se distribuyen las personas según su situación.\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Distribución de personas con discapacidad por región y zona de residencia en Costa Rica, 2023.](bitacora-2_files/figure-pdf/fig-region-zona-discapacidad-1.pdf){#fig-region-zona-discapacidad}\n:::\n:::\n\n\n\n\n\nEn la @fig-region-zona-discapacidad se presenta la distribución de personas con discapacidad por región y por zona de residencia (urbana o rural). La región que tiene la mayor cantidad de personas con discapacidad es la Central, y dentro de esta región la mayoría vive en zonas urbanas. En otras regiones como Chorotega, Pacífico Central y Huetar Caribe, la diferencia entre zonas urbanas y rurales no es tan grande. En Huetar Norte, la cantidad de personas con discapacidad en zonas rurales supera claramente a la de zonas urbanas. En general, en casi todas las regiones, las zonas urbanas tienden a tener una mayor concentración de personas con discapacidad, excepto en algunas regiones donde lo rural tiene más peso. Es importante tomar en cuenta que el alto número de personas que viven en la región Central podría hacer que muchos de los resultados del estudio estén más influenciados por lo que ocurre en esa región, y no reflejen con la misma fuerza lo que pasa en otras partes del país.\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Distribución porcentual de la condición de actividad laboral en Costa Rica, 2023.](bitacora-2_files/figure-pdf/fig-activ-discapacidad-1.pdf){#fig-activ-discapacidad}\n:::\n:::\n\n\n\n\n\nEn la @fig-activ-discapacidad se muestra la condición de actividad según el grado de discapacidad. Las personas sin discapacidad tienen el mayor porcentaje en la categoría de ocupados, con un 70.5%. Luego, conforme aumenta el grado de discapacidad, ese porcentaje va bajando. Por ejemplo, entre las personas con discapacidad severa, solo el 51.4% está ocupada. Por el contrario, el porcentaje de personas que están fuera de la fuerza de trabajo va aumentando a medida que se agrava el grado de discapacidad. En el grupo sin discapacidad, ese porcentaje es de 25.1%, y en el grupo con discapacidad severa sube a 44.6%. La proporción de personas desocupadas no varía tanto entre los grupos, aunque sí presenta una ligera alza en el grupo moderado.\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Distribución del ingreso per cápita del hogar en Costa Rica, 2023.](bitacora-2_files/figure-pdf/fig-discapacidad-ingreso-1.pdf){#fig-discapacidad-ingreso}\n:::\n:::\n\n\n\n\n\nEn la @fig-discapacidad-ingreso se puede ver cómo varía el ingreso per cápita del hogar según el grado de discapacidad. Se utilizó una escala logarítmica para representar mejor los valores extremos. Los diagramas de caja muestran que las personas sin discapacidad tienen una mediana de ingreso más alta que el resto. A medida que aumenta el grado de discapacidad, la mediana del ingreso baja. Además, la dispersión también es menor en los grupos con discapacidad severa o moderada. Se observan algunos valores extremos en todos los grupos, tanto por debajo como por encima de los rangos normales.\n\n\n\n\n\n::: {#tbl-ingreso-discapacidad .cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{llllll}\n\\caption{\\label{tab:tbl-ingreso-discapacidad}Distribución porcentual del ingreso per cápita por grado de discapacidad}\\\\\n\\toprule\nGrado de las personas en situación de discapacidad & I & II & III & IV & V\\\\\n\\midrule\nPersonas sin discapacidad & 23,77\\% & 21,37\\% & 20,02\\% & 18,33\\% & 16,51\\%\\\\\nPersonas con discapacidad de leve a moderada & 26,10\\% & 22,29\\% & 21,29\\% & 16,67\\% & 13,65\\%\\\\\nPersonas con discapacidad severa & 36,34\\% & 25,53\\% & 18,62\\% & 10,11\\% & 9,41\\%\\\\\n\\bottomrule\n\\multicolumn{6}{l}{\\rule{0pt}{1em}\\textit{Fuente: } ENADIS, Costa Rica. (2023)}\\\\\n\\end{longtable}\n\n\n:::\n:::\n\n\n\n\n\nEstos datos se complementan con la @tbl-ingreso-discapacidad, donde se resumen los principales valores del ingreso per cápita. La media en el grupo sin discapacidad es de ₡285,065, y va bajando hasta ₡213,770 en el grupo con discapacidad severa. Las medianas y cuartiles siguen una tendencia parecida: por ejemplo, la mediana en el grupo sin discapacidad es de ₡200,000, y en el grupo severo es de ₡140,000. En todos los casos, se nota que tanto los promedios como los rangos intercuartílicos son más bajos cuando hay discapacidad, especialmente si esta es moderada o severa.\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Distribución porcentual de personas ocupadas según tipo de empleo en Costa Rica, 2023.](bitacora-2_files/figure-pdf/fig-posicion-discapacidad-1.pdf){#fig-posicion-discapacidad}\n:::\n:::\n\n\n\n\n\nLa @fig-posicion-discapacidad muestra la posición en el trabajo principal según el grado de discapacidad. En el grupo sin discapacidad, la mayoría trabaja como empleado en una empresa privada (51.3%). En los grupos con discapacidad, este porcentaje va disminuyendo: en el grupo severo es de 42.6%. Por otro lado, el trabajo por cuenta propia tiene mayor peso en las personas con discapacidad. Por ejemplo, en el grupo severo, el 28.4% trabaja por cuenta propia, mientras que en el grupo sin discapacidad ese porcentaje es de 22.6%. También hay una pequeña diferencia en el empleo en casas particulares y en el porcentaje de personas que trabajan sin recibir pago, que son un poco más frecuentes en los grupos con discapacidad severa.\n\nEn cuanto a la cantidad de horas trabajadas semanalmente (@fig-horas-laboradas), se observa que en el grupo sin discapacidad la mayoría trabaja entre 40 y 48 horas por semana (56.4%). En los otros grupos, ese porcentaje va bajando. Las personas con discapacidad severa tienen el porcentaje más bajo en esta categoría (40.5%). En cambio, en las categorías de menos de 15 horas y de 15 a menos de 40 horas, se ven porcentajes más altos en los grupos con discapacidad. Por ejemplo, el 16.5% de las personas con discapacidad severa trabaja menos de 15 horas, mientras que en el grupo sin discapacidad ese valor es de 5.6%. Esto indica que en los grupos con discapacidad hay una mayor presencia de jornadas reducidas.\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Tendencia del ingreso según nivel de discapacidad en Costa Rica, 2023.](bitacora-2_files/figure-pdf/fig-puntaje-discapacidad-ingreso-1.pdf){#fig-puntaje-discapacidad-ingreso}\n:::\n:::\n\n\n\n\n\nEn la @fig-puntaje-discapacidad-ingreso, lo que se puede identificar es la relación entre nivel de discapacidad y nivel de ingreso. Este gráfico muestra que, en general, a mayor puntaje de discapacidad, menor tiende a ser el ingreso mensual per cápita del hogar, lo que sugiere una relación negativa entre ambas variables. La principal característica observada es la existencia de una amplia dispersión en los ingresos, lo que indica que, si bien la discapacidad afecta el nivel económico, también hay otros factores que inciden. Uno de los desafíos del análisis es precisamente esta variabilidad: el gráfico no considera directamente otros determinantes del ingreso como el nivel educativo, la región, o las políticas de inclusión laboral. A pesar de ello, el patrón decreciente refuerza la idea de que las personas con mayores limitaciones funcionales enfrentan barreras adicionales para acceder a empleos bien remunerados, lo cual impacta directamente su bienestar económico.\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Distribución de las horas laboradas en Costa Rica, 2023.](bitacora-2_files/figure-pdf/fig-horas-laboradas-1.pdf){#fig-horas-laboradas}\n:::\n:::\n\n\n\n\nEn la @fig-horas-laboradas se presencia una mayor cantidad de personas que laboran menos de 15 horas en comparación a los demás grupos de personas sin embargo es curioso notar como igual existe un grupo muy amplio y parecido en porcentaje a los demás que laboran de 40 a 48 horas lo cual y es que al analizar @fig-discapacidad-ingreso podemos notar que las estadísticas de los hogares son realmente parecidas a excepción de valores \"outliers\" ya que sin estos los cuatro grupos tienen una media de aproximadamente 250.000 colones. Esto deja como hipótesis que muchos hogares cuya fuente de ingreso sufre de una discapacidad severa tienen muchas necesidades económicas por lo que igualmente deben trabajar una alta cantidad de horas.\n\n\n\n\n\n\n\n\n\n\n\n\n#### Formato tidy\n\nPara el análisis se utilizó una versión depurada de la base de datos ENADIS 2023, la cual fue transformada para tener el formato tidy, en donde cada fila representa una persona encuestada y cada columna corresponde a una variable claramente definida. Se verificó que todas las variables presentaran la clase adecuada mediante la función `str()`, como se muestra más abajo, confirmando que las variables numéricas, como la edad (`A5`) o los ingresos (`ING_PERCAPITA_HOGAR`), se mantienen como numeric, mientras que las categóricas, como el sexo (`A4`), región (`region`) o condición de actividad (`condic_activi`), están correctamente codificadas como factores (`factor`). Además, las variables fueron renombradas con nombres intuitivos y estandarizados, facilitando su interpretación y manipulación posterior.\n\nLos valores faltantes (`NA`) fueron identificados, especialmente en variables relacionadas con el empleo como `B8a` (posición en el trabajo) y `B7` (cantidad de horas laboradas). Su presencia se explica porque algunas personas no forman parte de la población económicamente activa, por lo que estos valores fueron tratados adecuadamente en los análisis posteriores mediante filtrado y uso de funciones como `drop_na()` cuando era pertinente.\n\nEsta estructura y limpieza de la base garantiza una exploración coherente y reproducible, cumpliendo con los principios de orden, claridad y transparencia necesarios para un análisis cuantitativo riguroso.\n\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\ntibble [9,533 x 10] (S3: tbl_df/tbl/data.frame)\n $ A5                 : num [1:9533] 45 45 33 41 51 22 43 53 53 45 ...\n  ..- attr(*, \"label\")= chr \"A5_Edad\"\n  ..- attr(*, \"format.spss\")= chr \"F11.0\"\n  ..- attr(*, \"display_width\")= int 11\n $ A4                 : Factor w/ 2 levels \"Hombre\",\"Mujer\": 2 2 2 1 1 1 2 1 1 2 ...\n  ..- attr(*, \"label\")= chr \"A4_Sexo\"\n $ region             : Factor w/ 6 levels \"Central\",\"Chorotega\",..: 1 1 1 1 1 1 1 1 1 1 ...\n  ..- attr(*, \"label\")= chr \"Región de planificación\"\n $ zona               : Factor w/ 2 levels \"Urbana\",\"Rural\": 1 1 1 1 1 1 1 1 1 1 ...\n  ..- attr(*, \"label\")= chr \"Zona (Urbana - Rural)\"\n $ Cap_grado          : Factor w/ 4 levels \"No\",\"Leve\",\"Moderado\",..: 1 1 3 1 1 2 2 3 1 3 ...\n  ..- attr(*, \"label\")= chr \"Grado de dificultad en la capacidad\"\n $ ING_PERCAPITA_HOGAR: num [1:9533] 241000 305000 1250000 185889 87500 ...\n  ..- attr(*, \"label\")= chr \"Ingresos per cápita del hogar\"\n  ..- attr(*, \"format.spss\")= chr \"F8.0\"\n  ..- attr(*, \"display_width\")= int 21\n $ condic_activi      : Factor w/ 3 levels \"Ocupados/as\",..: 3 2 3 1 1 1 1 1 1 3 ...\n  ..- attr(*, \"label\")= chr \"Condición de actividad\"\n $ B8a                : Factor w/ 6 levels \"Patrono/a o empleador/a\",..: NA NA NA 3 2 3 5 3 2 NA ...\n  ..- attr(*, \"label\")= chr \"B8a_Posición en el trabajo principal\"\n $ B7                 : Factor w/ 5 levels \"Menos de 15 horas\",..: NA NA NA 3 3 3 4 3 3 NA ...\n  ..- attr(*, \"label\")= chr \"B7_Cantidad de horas laboradas en el trabajo principal\"\n $ Nivel_Instru       : Factor w/ 6 levels \"Sin nivel de instrucción\",..: 5 5 5 4 4 4 5 6 6 4 ...\n  ..- attr(*, \"label\")= chr \"A15_ Nivel de instrucción (recodificada)\"\n```\n\n\n:::\n:::\n\n\n\n\n\\newpage\n\n#### Tablas\n\n\n\n\n\n::: {#tbl-pos_trab_vs_grad_disc .cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{>{\\raggedright\\arraybackslash}p{5cm}llll}\n\\caption{\\label{tab:tbl-pos_trab_vs_grad_disc}Distribución porcentual del grado de dificultad en la capacidad según la posición en el trabajo}\\\\\n\\toprule\nB8a & No & Leve & Moderado & Severo\\\\\n\\midrule\nPatrono/a o empleador/a & 59,85\\% & 19,45\\% & 16,21\\% & 4,49\\%\\\\\nTrabajador/a por cuenta propia & 42,66\\% & 22,14\\% & 21,11\\% & 14,09\\%\\\\\nEmpleado/a para un patrón/a o empresa privada & 49,95\\% & 21,59\\% & 17,58\\% & 10,88\\%\\\\\nEmpleado/a del sector público & 46,27\\% & 18,41\\% & 21,39\\% & 13,93\\%\\\\\nEmpleado/a  de casas particulares & 34,96\\% & 22,25\\% & 21,76\\% & 21,03\\%\\\\\n\\addlinespace\nAyudante sin recibir pago & 35,29\\% & 20,59\\% & 23,53\\% & 20,59\\%\\\\\n\\bottomrule\n\\multicolumn{5}{l}{\\rule{0pt}{1em}\\textit{Fuente: } ENADIS, Costa Rica. (2023)}\\\\\n\\end{longtable}\n\n\n:::\n:::\n\n\n\n\n\nEsta tabla muestra cómo varía el grado de dificultad en la capacidad de las personas con discapacidad según su posición en el empleo. Se observa que las personas que ocupan cargos como patronos o empleadores presentan mayoritariamente ninguna dificultad (59,85\\%), mientras que las personas que trabajan como ayudantes sin recibir pago o como empleadas de casas particulares concentran porcentajes más altos en los niveles de dificultad severa (20,59\\% y 21,03\\% respectivamente).\n\n\n\n\n\n::: {#tbl-condic_actividad_vs_grad_disc .cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{llll}\n\\caption{\\label{tab:tbl-condic_actividad_vs_grad_disc}Distribución porcentual de la condición de actividad laboral según grado de dificultad en la capacidad}\\\\\n\\toprule\nCap\\_grado & Ocupados/as & Desocupados/as & Fuera de la fuerza de trabajo\\\\\n\\midrule\nNo & 70,51\\% & 4,44\\% & 25,05\\%\\\\\nLeve & 67,99\\% & 4,07\\% & 27,94\\%\\\\\nModerado & 61,70\\% & 5,28\\% & 33,02\\%\\\\\nSevero & 51,44\\% & 3,94\\% & 44,62\\%\\\\\n\\bottomrule\n\\multicolumn{4}{l}{\\rule{0pt}{1em}\\textit{Fuente: } ENADIS, Costa Rica. (2023)}\\\\\n\\end{longtable}\n\n\n:::\n:::\n\n\n\n\n\nLa tabla presenta la condición de actividad laboral (ocupado/a, desocupado/a, fuera de la fuerza de trabajo) en función del grado de dificultad. Se destaca que a medida que aumenta la severidad de la dificultad, disminuye la proporción de personas ocupadas (70,51\\% en el grupo sin dificultad vs. 51,44\\% en el grupo con dificultad severa), mientras que aumenta notablemente el porcentaje de personas fuera de la fuerza de trabajo (25,05\\% a 44,62\\%).\n\n\n\n\n\n::: {#tbl-promedio_ingreso_vs_pos_y_grado .cell}\n::: {.cell-output-display}\n\n\\begin{longtable}[t]{lrrrr}\n\\caption{\\label{tab:tbl-promedio_ingreso_vs_pos_y_grado}Promedio del ingreso per cápita del hogar según condición de actividad y grado de discapacidad}\\\\\n\\toprule\ncondic\\_activi & No & Leve & Moderado & Severo\\\\\n\\midrule\nOcupados/as & 326720 & 300298 & 298785 & 269744\\\\\nDesocupados/as & 125695 & 106102 & 113802 & 101167\\\\\nFuera de la fuerza de trabajo & 196078 & 171137 & 173547 & 159196\\\\\n\\bottomrule\n\\multicolumn{5}{l}{\\rule{0pt}{1em}\\textit{Fuente: } ENADIS, Costa Rica. (2023)}\\\\\n\\end{longtable}\n\n\n:::\n:::\n\n\n\n\n\nEsta tabla presenta el ingreso per cápita promedio del hogar en función de la condición de actividad y del grado de dificultad. Se evidencia una disminución sistemática del ingreso conforme aumenta la severidad de la discapacidad. Además, las personas ocupadas muestran ingresos más altos que las desocupadas o las que están fuera de la fuerza de trabajo, sin importar el grado de discapacidad.\n\n\n\n\n\n::: {#tbl-cuadro_frec_rel_pos_grado .cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 24 x 8\n   Cap_grado n        `Patrono/a o empleador/a` `Trabajador/a por cuenta propia`\n   <fct>     <chr>    <chr>                     <chr>                           \n 1 No        24 000%  8.17%                     0.00%                           \n 2 No        66 300%  0.00%                     22.58%                          \n 3 No        150 600% 0.00%                     0.00%                           \n 4 No        37 200%  0.00%                     0.00%                           \n 5 No        14 300%  0.00%                     0.00%                           \n 6 No        1 200%   0.00%                     0.00%                           \n 7 Leve      7 800%   5.91%                     0.00%                           \n 8 Leve      34 400%  0.00%                     26.08%                          \n 9 Leve      65 100%  0.00%                     0.00%                           \n10 Leve      14 800%  0.00%                     0.00%                           \n# i 14 more rows\n# i 4 more variables: `Empleado/a para un patrón/a o empresa privada` <chr>,\n#   `Empleado/a del sector público` <chr>,\n#   `Empleado/a  de casas particulares` <chr>,\n#   `Ayudante sin recibir pago` <chr>\n```\n\n\n:::\n:::\n\n\n\n\n\n\n#### Gráficos\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Distribución del grupo ocupacional según horas trabajadas y presencia de enfermedades crónicas en Costa Rica, 2023.](bitacora-2_files/figure-pdf/fig-doble_grafico-1.pdf){#fig-doble_grafico}\n:::\n:::\n\n\n\n\n\n\n## Propuesta Metodológica\n\n**Comentario**: En esta sección se expondrán las bases teóricas de la prueba de Kruskal-Wallis y la prueba Chi-cuadrado de independencia, así como las herramientas utilizadas para la implementación del código maqueta\n\n### Método #1: Prueba de Kruskal-Wallis\n\nSegún @ostertagova2014kruskal, la prueba de Kruskal-Wallis es una buena opción cuando se quiere comparar varios grupos pero los datos no cumplen con la normalidad. \n\n::: {.callout-note title=\"Definición 2.1 (Prueba de Kruskal-Wallis)\"}\nLa prueba de Kruskal-Wallis sirve para ver si las distribuciones de una variable son iguales entre varios grupos. Se basa en rangos y no en los valores originales. El estadístico se calcula con la fórmula:\n\n\\[\nH = \\frac{12}{N(N+1)} \\sum_{i=1}^{k} \\frac{R_i^2}{n_i} - 3(N+1)\n\\]\n\ndonde \\( N \\) es el total de observaciones, \\( k \\) el número de grupos, \\( n_i \\) el tamaño del grupo \\( i \\), y \\( R_i \\) la suma de los rangos del grupo \\( i \\).\n:::\n\nLo que se hace es juntar todos los datos del ingreso, ordenarlos y asignarles un rango sin importar a qué grupo pertenecen. Luego se sacan los rangos por grupo y se calcula el valor de la prueba. La idea es ver si hay diferencias entre las distribuciones de ingreso según el grado de discapacidad (sin, leve, moderada y severa).\n\nPara decidir si las diferencias entre los grupos son significativas, se compara el valor p que se obtiene con un nivel de significancia, que normalmente es 0.05. Si el valor p es menor a 0.05, se rechaza la hipótesis nula y se concluye que sí hay diferencias entre los grupos.\n\nEsta prueba no necesita que los datos sean normales ni que tengan la misma varianza, por eso es útil para este tipo de datos sociales. También es resistente a valores extremos, lo cual es importante cuando se trabaja con ingresos. Por estas razones se eligió este método para el análisis.\n\nEn esta prueba, la **hipótesis nula** plantea que no hay diferencias entre las distribuciones de los grupo, mientras que la **alternativa** indica que al menos uno de los grupos tiene una distribución diferente. La prueba permite detectar si esas diferencias son significativas.\n\n### Método #2: Prueba Chi-cuadrado de independencia\n\nLa prueba Chi-cuadrado de independencia se va a usar para analizar si existe relación entre el grado de discapacidad y otras variables categóricas. Esta prueba es útil cuando se quiere ver si dos variables categóricas están asociadas o si son independientes.\n\nSegún @mchugh2013chi, esta prueba compara lo que se observa en los datos con lo que se esperaría si no hubiera relación entre las variables. Si las diferencias entre lo observado y lo esperado son muy grandes, entonces se considera que hay una relación entre las variables.\n\n::: {.callout-note title=\"Definición 2.2 (Prueba Chi-cuadrado de independencia)\"}\nEl estadístico de la prueba se calcula con la fórmula:\n\n\\[\n\\chi^2 = \\sum_{i=1}^r \\sum_{j=1}^c \\frac{(O_{ij} - E_{ij})^2}{E_{ij}}\n\\]\n\ndonde \\( O_{ij} \\) es la frecuencia observada en la celda \\( i, j \\), y \\( E_{ij} \\) es la frecuencia esperada, calculada como:\n\n\\[\nE_{ij} = \\frac{(F_i)(C_j)}{N}\n\\]\n\nsiendo \\( F_i \\) el total de la fila \\( i \\), \\( C_j \\) el total de la columna \\( j \\), y \\( N \\) el número total de casos.\n:::\n\nLa **hipótesis nula** de esta prueba dice que las dos variables no tienen relación, o sea, que son independientes. En cambio, la **hipótesis alternativa** dice que sí hay una relación entre ellas.\n\nPara saber si las diferencias son significativas, se usa un valor de referencia que se llama nivel de significancia (generalmente 0.05). Si el valor p que se obtiene es menor a 0.05, se rechaza la hipótesis nula y se concluye que sí hay una asociación entre las variables.\n\nEsta prueba es muy útil en investigaciones sociales porque no requiere que los datos sean normales ni que los grupos tengan tamaños iguales. \n\n### Método #3: Medida de asociación con V de Cramer\n\n::: {.callout-note title=\"Definición 2.3 (V de Cramer)\"}\nLa V de Cramer es una medida de asociación entre dos variables categóricas. Se utiliza comúnmente después de realizar una prueba chi-cuadrado para cuantificar la intensidad de la relación. Su fórmula es:\n\n\\[\nV = \\sqrt{ \\frac{\\chi^2}{N \\cdot (k - 1)} }\n\\]\n\ndonde:\n\n- \\( \\chi^2 \\) es el estadístico de la prueba chi-cuadrado de independencia,\n- \\( N \\) es el número total de observaciones,\n- \\( k \\) es el menor entre el número de filas \\( r \\) o el número de columnas \\( c \\), es decir: \\( k = \\min(r, c) \\).\n\nEl valor de \\( V \\) está acotado entre 0 y 1. Un valor cercano a 0 indica poca o ninguna asociación entre las variables, mientras que un valor cercano a 1 indica una asociación fuerte.\n:::\n\nLa V de Cramer se utiliza para saber qué tan fuerte es la relación entre dos variables categóricas una vez que se ha determinado que sí existe asociación (por ejemplo, tras rechazar la hipótesis nula de independencia con una prueba chi-cuadrado). Su valor va de 0 a 1, donde 0 indica ninguna relación y 1 indica una relación perfecta.\n\nAunque no tiene una regla universal, existen guías orientativas para interpretar la magnitud de V. Por ejemplo, valores menores a 0.1 suelen interpretarse como una relación débil, entre 0.1 y 0.3 como moderada, y mayores a 0.3 como fuerte, dependiendo también del tamaño de la tabla.\n\nEs especialmente útil cuando hay tablas grandes o cuando se quiere comparar la fuerza de asociación entre distintas parejas de variables categóricas.\n\n### Código\n\nSe carga la base de datos, con todas las variables que se utilizarán para el análisis:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Se seleccionan las variables para las pruebas de hipótesis\nenadis <- env$enadis_completa %>% \n  select(A5, Cap_grado, ING_PERCAPITA_HOGAR, condic_activi, B8a, B7)\n\n# Se factorizan las columnas\nenadis <- env$enadis %>% \n  mutate(across(where(~ is.labelled(.x) || is.character(.x)), as_factor))\n\n# Se filtran por personas entre 18 y 65 años\nenadis <- enadis %>% filter(A5 >= 18 & A5 <= 65)\n```\n:::\n\n\n\n\nSe plantean las hipótesis de cada prueba:\n\n- Prueba 1: Ingreso per cápita del hogar vs grado de discapacidad\n\n  - \\( H_0 \\): Las distribuciones del ingreso per cápita son iguales entre los distintos grados de discapacidad.\n\n  - \\( H_1 \\): Al menos un grupo tiene una distribución distinta.\n  \n- Prueba 2: Condición de actividad vs grado de discapacidad\n\n  - \\( H_0 \\): No existe asociación entre la condición de actividad y el grado de discapacidad.\n\n  - \\( H_1 \\): Sí existe asociación.\n\n- Prueba 3: Horas de trabajo en el empleo principal vs grado de discapacidad\n\n  - \\( H_0 \\): No existe asociación entre las horas trabajadas en el empleo principal y el grado de discapacidad\n\n  - \\( H_1 \\): Sí existe asociación\n  \n- Prueba 4: Tipo de puesto de trabajo vs grado de discapacidad\n\n  - \\( H_0 \\): No existe asociación entre el tipo de puesto de trabajo y el grado de discapacidad\n\n  - \\( H_1 \\): Sí existe asociación\n  \nSe ejecutan las pruebas:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Prueba 1:\n\nkruskal.test(ING_PERCAPITA_HOGAR ~ Cap_grado, data = enadis)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tKruskal-Wallis rank sum test\n\ndata:  ING_PERCAPITA_HOGAR by Cap_grado\nKruskal-Wallis chi-squared = 192.41, df = 3, p-value < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\n# Prueba 2: \n\nchisq.test(table(enadis$Cap_grado, enadis$condic_activi))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  table(enadis$Cap_grado, enadis$condic_activi)\nX-squared = 219.33, df = 6, p-value < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\n# Prueba 3: \n\n# Se descartan los valores NA de las horas trabajadas \n\nenadis_filtrado <- enadis %>%\n  filter(!is.na(B7)) %>%\n  mutate(B7 = droplevels(B7))\n\nchisq.test(table(enadis_filtrado$Cap_grado, enadis_filtrado$B7))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  table(enadis_filtrado$Cap_grado, enadis_filtrado$B7)\nX-squared = 173.32, df = 9, p-value < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\n# Prueba 4: \n\n#La tabla de contingencia solo contempla ocupados\nchisq.test(table(enadis$Cap_grado[enadis$condic_activi == \"Ocupados/as\"],\n                 enadis$B8a[enadis$condic_activi == \"Ocupados/as\"]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  table(enadis$Cap_grado[enadis$condic_activi == \"Ocupados/as\"],     enadis$B8a[enadis$condic_activi == \"Ocupados/as\"])\nX-squared = 114.06, df = 15, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n\n\n### Construcción de fichas de resultados\n\n#### Hallazgo 1\n\n-   **Nombre del hallazgo o resultado**: Ingreso per cápita según grado de discapacidad.\n\n-   **Resumen en una oración**: Las personas con diferentes grados de discapacidad no tienen el mismo ingreso per cápita del hogar.\n\n-   **Principal característica**: En la @fig-discapacidad-ingreso, @tbl-promedio_ingreso_vs_pos_y_grado y @tbl-ingreso-discapacidad se ve que los ingresos bajan conforme el grado de discapacidad es mayor. Además, se aplicó una prueba Kruskal-Wallis y el resultado fue significativo (\\( \\chi^2 \\) = 192.41, gl = 3, p < 2.2e-16), lo que indica que hay diferencias claras entre los grupos.\n\n-   **Problemas o posibles desafíos**: El @fig-discapacidad-ingreso expone un alto nivel de variabilidad en los ingresos y no distingue otros factores de contexto que podrían explicar la variación.\n\n-   **Resumen en un párrafo**: Al comparar los ingresos per cápita entre los distintos grados de discapacidad, se nota que quienes no tienen discapacidad ganan más en promedio y tienen ingresos más variados. A medida que la discapacidad es más severa, los ingresos bajan. Esta diferencia no se da por casualidad, ya que la prueba estadística aplicada muestra que sí hay una diferencia significativa en los ingresos entre los distintos grupos.\n\n\n#### Hallazgo 2\n\n-   **Nombre del hallazgo o resultado**: Relación entre grado de discapacidad y situación laboral.\n\n-   **Resumen en una oración**: La condición laboral de las personas cambia dependiendo del grado de discapacidad.\n\n-   **Principal característica**: En la @fig-activ-discapacidad se ve que quienes tienen discapacidad, sobre todo severa, están más fuera de la fuerza de trabajo. La prueba chi-cuadrado (\\( \\chi^2 \\) = 219.33, gl = 6, p < 2.2e-16) confirmó que sí hay una relación entre estas dos variables.\n\n-   **Problemas o posibles desafíos**: Esto puede afectar el acceso al empleo para las personas con discapacidad, aunque no se sabe por qué pasa solo con estos datos.\n\n-   **Resumen en un párrafo**: Al revisar los datos como en la @tbl-condic_actividad_vs_grad_disc, se nota que las personas sin discapacidad están más ocupadas laboralmente, mientras que en los grupos con discapacidad hay más personas fuera de la fuerza de trabajo. Esta diferencia se ve más en el grupo con discapacidad severa. La prueba chi-cuadrado muestra que esta diferencia no es al azar, sino que sí hay relación entre el grado de discapacidad y la condición laboral.\n\n#### Hallazgo 3\n\n-   **Nombre del hallazgo o resultado**: Horas trabajadas y grado de discapacidad.\n\n-   **Resumen en una oración**: Las horas que trabaja una persona cambian según su grado de discapacidad.\n\n-   **Principal característica**: En los cuadros se ve que las personas con discapacidad severa trabajan menos horas, y la prueba chi-cuadrado (\\( \\chi^2 \\) = 173.32, gl = 9, p < 2.2e-16) dice que esta diferencia es significativa.\n\n-   **Problemas o posibles desafíos**: La base no permite saber si las personas trabajan menos horas por decisión propia, por barreras del entorno o por motivos de salud. Esto hace difícil entender si estas diferencias se deben a la disponibilidad, a la demanda laboral o a una limitación funcional directa.\n\n-   **Resumen en un párrafo**: Según los datos, las personas sin discapacidad tienden a trabajar jornadas completas, mientras que en los grupos con discapacidad hay más gente con jornadas cortas, especialmente los que tienen discapacidad severa. Esta diferencia fue confirmada con una prueba estadística, que indica que hay una relación significativa entre el grado de discapacidad y la cantidad de horas trabajadas.\n\n#### Hallazgo 4\n\n-   **Nombre del hallazgo o resultado**: Tipo de trabajo y grado de discapacidad (personas ocupadas).\n\n-   **Resumen en una oración**: El tipo de puesto de trabajo cambia según el grado de discapacidad, incluso entre personas que sí tienen empleo.\n\n-   **Principal característica**: En la @tbl-pos_trab_vs_grad_disc o en la @fig-posicion-discapacidad se ve que las personas con discapacidad severa trabajan más por cuenta propia o en casas particulares. La prueba chi-cuadrado (\\( \\chi^2 \\) = 114.06, gl = 15, p < 2.2e-16) confirma que hay diferencias reales entre los grupos.\n\n-   **Problemas o posibles desafíos**: Aunque todas las personas analizadas están ocupadas, los datos no permiten saber si las diferencias en el tipo de trabajo son por elección, por falta de oportunidades o por discriminación laboral. Esto puede limitar la interpretación del acceso real a empleos de calidad.\n\n-   **Resumen en un párrafo**: Cuando se compara el tipo de trabajo entre personas que están ocupadas, se nota que quienes no tienen discapacidad tienden a estar en empleos formales, como en empresas privadas. En cambio, las personas con discapacidad, sobre todo severa, están más en trabajos por cuenta propia o en puestos informales. Esta diferencia también fue confirmada con una prueba estadística que muestra que el tipo de trabajo está relacionado con el grado de discapacidad.\n\n#### Hallazgo 5\n\n-   **Nombre del hallazgo o resultado**: Relación entre carga horaria, grupo ocupacional y enfermedades crónicas.\n\n-   **Resumen en una oración**: La distribución del grupo ocupacional varía según la cantidad de horas trabajadas y la presencia de enfermedades crónicas.\n\n-   **Principal característica**: En el gráfico @fig-doble_grafico se observa que las personas con enfermedades crónicas tienden a concentrarse más en ocupaciones no calificadas, especialmente en las jornadas de menor duración. En contraste, entre quienes no presentan enfermedades, hay una mayor proporción en ocupaciones calificadas, en particular en las jornadas más extensas.\n\n-   **Problemas o posibles desafíos**: La visualización no permite distinguir si la relación se debe a discriminación laboral, limitaciones de salud funcional o decisiones personales. Además, no controla por otras variables como edad, educación o región\n\n-   **Resumen en un párrafo**: El gráfico @fig-doble_grafico muestra un patrón claro: las personas con enfermedades crónicas tienden a desempeñar ocupaciones menos calificadas, en especial cuando trabajan menos de 40 horas semanales. En cambio, las personas sin enfermedades están más representadas en ocupaciones calificadas y en jornadas completas o extensas. Esto sugiere una posible relación entre salud crónica y calidad del empleo. La asociación podría estar mediada por restricciones funcionales, discriminación o menor acceso a puestos formales, lo que refuerza la necesidad de políticas de inclusión laboral sensibles a la salud.\n\n## Actualización de la UVE de Godwin\n\n![UVE Heurística](UVE 2.png)\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{},\"value\":[]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}