project:
  type: book
  output-dir: "docs"

lang: es

book:
  title: "Bitácoras, CA-0303 (I-2025)"
  author: 
    - "Jose Andrey Prado Rojas-C36174" 
    - "José Carlos Quintero Cedeño-C26152" 
    - "Diego Alberto Vega Víquez-C38367" 
  date: today
  publisher: "Universidad de Costa Rica"
  repo-actions: [edit]
  downloads: [pdf, epub]
  chapters:
    - "index.qmd"        # es un archivo obligatorio en un proyecto de libro (type: book)
    - "bitacora-1.qmd"
    - "bitacora-2.qmd"
    - "bitacora-3.qmd"

bibliography: references.bib
csl: apa.csl
nocite: |
  @*

format:
  # html:
      # Pueden usar cualquier tema de los que están aca:
      # https://quarto.org/docs/output-formats/html-themes.html a excepción de
      # los oscuros porque no entiende nada.
    # theme: cosmo
  pdf:
    documentclass: book       # Clase de documento (book, report, etc.)
    papersize: letter         # Tamaño del papel (A4, letter)
    fontsize: 12pt            # Tamaño de fuente
    linestretch: 1
    geometry:  # Configuración de márgenes y diseño de página (paquete LaTeX 'geometry')
      - top=3cm       # Margen superior 
      - bottom=3cm    # Margen inferior 
      - left=3cm      # Margen izquierdo 
      - right=2.5cm     # Margen derecho 
      - headheight=15pt  # Altura mínima reservada para el encabezado (15 puntos)
      - footskip=1.25cm   # Espacio entre el pie de página y el final del texto (1.5cm)
    classoption: oneside  # Elimina la distinción entre páginas pares/impares
    openany: true         # Permite que los capítulos comiencen en cualquier página
    top-level-division: chapter #define cuál es el nivel jerárquico que se usará para estructurar el doc
    number-sections: false  # Desactiva numeración automática


execute:
  freeze: auto
  cache: true

from: markdown+tex_math_single_backslash+emoji
link-external-newwindow: true
